import { TikTokProduct, WholesaleSource } from "@/types";

export const MOCK_PRODUCTS: TikTokProduct[] = [
  {
    id: "p1",
    name: "LED Cloud Night Light",
    category: "Home Decor",
    tiktokViews: 48200000,
    tiktokHashtag: "#cloudlight",
    tiktokSellPrice: 29.99,
    imageUrl: "",
    trending: true,
    addedAt: "2026-06-01",
  },
  {
    id: "p2",
    name: "Magnetic Eyelashes Kit",
    category: "Beauty",
    tiktokViews: 31500000,
    tiktokHashtag: "#magneticlashes",
    tiktokSellPrice: 19.99,
    imageUrl: "",
    trending: true,
    addedAt: "2026-06-02",
  },
  {
    id: "p3",
    name: "Insulated Water Bottle 40oz",
    category: "Fitness",
    tiktokViews: 22800000,
    tiktokHashtag: "#stanleydupe",
    tiktokSellPrice: 24.99,
    imageUrl: "",
    trending: true,
    addedAt: "2026-06-03",
  },
  {
    id: "p4",
    name: "Portable Blender",
    category: "Kitchen",
    tiktokViews: 19700000,
    tiktokHashtag: "#portableblender",
    tiktokSellPrice: 34.99,
    imageUrl: "",
    trending: true,
    addedAt: "2026-06-04",
  },
  {
    id: "p5",
    name: "Silicone Ice Cube Tray (Large)",
    category: "Kitchen",
    tiktokViews: 15400000,
    tiktokHashtag: "#icecubetray",
    tiktokSellPrice: 12.99,
    imageUrl: "",
    trending: false,
    addedAt: "2026-06-05",
  },
  {
    id: "p6",
    name: "Gua Sha Face Tool Set",
    category: "Beauty",
    tiktokViews: 27300000,
    tiktokHashtag: "#guasha",
    tiktokSellPrice: 22.99,
    imageUrl: "",
    trending: true,
    addedAt: "2026-06-06",
  },
  {
    id: "p7",
    name: "RGB Gaming LED Strip Lights",
    category: "Home Decor",
    tiktokViews: 36100000,
    tiktokHashtag: "#ledstrip",
    tiktokSellPrice: 18.99,
    imageUrl: "",
    trending: true,
    addedAt: "2026-06-07",
  },
  {
    id: "p8",
    name: "Electric Scalp Massager",
    category: "Beauty",
    tiktokViews: 11200000,
    tiktokHashtag: "#scalpmassager",
    tiktokSellPrice: 27.99,
    imageUrl: "",
    trending: false,
    addedAt: "2026-06-08",
  },
];

export const MOCK_SOURCES: WholesaleSource[] = [
  // LED Cloud Night Light
  {
    id: "s1a",
    productId: "p1",
    platform: "Alibaba",
    supplierName: "Shenzhen LightCo",
    unitPrice: 4.2,
    moq: 50,
    currency: "USD",
    link: "https://www.alibaba.com",
    shippingCostPerUnit: 1.1,
    importDutyPct: 5,
    leadTimeDays: 18,
    rating: 4.8,
    inStock: true,
  },
  {
    id: "s1b",
    productId: "p1",
    platform: "DHgate",
    supplierName: "CloudLux Factory",
    unitPrice: 5.1,
    moq: 20,
    currency: "USD",
    link: "https://www.dhgate.com",
    shippingCostPerUnit: 1.4,
    importDutyPct: 5,
    leadTimeDays: 22,
    rating: 4.5,
    inStock: true,
  },
  {
    id: "s1c",
    productId: "p1",
    platform: "AliExpress",
    supplierName: "Dream Lights Store",
    unitPrice: 6.3,
    moq: 5,
    currency: "USD",
    link: "https://www.aliexpress.com",
    shippingCostPerUnit: 1.8,
    importDutyPct: 5,
    leadTimeDays: 25,
    rating: 4.6,
    inStock: true,
  },
  // Magnetic Eyelashes
  {
    id: "s2a",
    productId: "p2",
    platform: "Alibaba",
    supplierName: "BeautyPro Wholesale",
    unitPrice: 1.8,
    moq: 100,
    currency: "USD",
    link: "https://www.alibaba.com",
    shippingCostPerUnit: 0.5,
    importDutyPct: 6.5,
    leadTimeDays: 15,
    rating: 4.9,
    inStock: true,
  },
  {
    id: "s2b",
    productId: "p2",
    platform: "Made-in-China",
    supplierName: "Lash Kingdom",
    unitPrice: 2.1,
    moq: 50,
    currency: "USD",
    link: "https://www.made-in-china.com",
    shippingCostPerUnit: 0.6,
    importDutyPct: 6.5,
    leadTimeDays: 20,
    rating: 4.4,
    inStock: true,
  },
  {
    id: "s2c",
    productId: "p2",
    platform: "Faire",
    supplierName: "Glam Essentials",
    unitPrice: 4.5,
    moq: 12,
    currency: "USD",
    link: "https://www.faire.com",
    shippingCostPerUnit: 0.8,
    importDutyPct: 0,
    leadTimeDays: 7,
    rating: 4.7,
    inStock: false,
  },
  // Insulated Water Bottle
  {
    id: "s3a",
    productId: "p3",
    platform: "Alibaba",
    supplierName: "HydroFactory Ningbo",
    unitPrice: 5.5,
    moq: 100,
    currency: "USD",
    link: "https://www.alibaba.com",
    shippingCostPerUnit: 1.5,
    importDutyPct: 3.4,
    leadTimeDays: 20,
    rating: 4.7,
    inStock: true,
  },
  {
    id: "s3b",
    productId: "p3",
    platform: "Global Sources",
    supplierName: "StainlessPro Exports",
    unitPrice: 6.2,
    moq: 50,
    currency: "USD",
    link: "https://www.globalsources.com",
    shippingCostPerUnit: 1.6,
    importDutyPct: 3.4,
    leadTimeDays: 18,
    rating: 4.6,
    inStock: true,
  },
  // Portable Blender
  {
    id: "s4a",
    productId: "p4",
    platform: "Alibaba",
    supplierName: "BlendTech Manufacturing",
    unitPrice: 7.8,
    moq: 50,
    currency: "USD",
    link: "https://www.alibaba.com",
    shippingCostPerUnit: 2.1,
    importDutyPct: 3.7,
    leadTimeDays: 22,
    rating: 4.8,
    inStock: true,
  },
  {
    id: "s4b",
    productId: "p4",
    platform: "DHgate",
    supplierName: "JuiceMaster Pro",
    unitPrice: 9.2,
    moq: 20,
    currency: "USD",
    link: "https://www.dhgate.com",
    shippingCostPerUnit: 2.4,
    importDutyPct: 3.7,
    leadTimeDays: 18,
    rating: 4.5,
    inStock: true,
  },
  // Ice Cube Tray
  {
    id: "s5a",
    productId: "p5",
    platform: "Alibaba",
    supplierName: "SiliconeMolds Co",
    unitPrice: 0.9,
    moq: 200,
    currency: "USD",
    link: "https://www.alibaba.com",
    shippingCostPerUnit: 0.4,
    importDutyPct: 3.3,
    leadTimeDays: 14,
    rating: 4.6,
    inStock: true,
  },
  {
    id: "s5b",
    productId: "p5",
    platform: "Tundra",
    supplierName: "KitchenPlus Wholesale",
    unitPrice: 2.8,
    moq: 24,
    currency: "USD",
    link: "https://www.tundra.com",
    shippingCostPerUnit: 0.6,
    importDutyPct: 0,
    leadTimeDays: 5,
    rating: 4.3,
    inStock: true,
  },
  // Gua Sha
  {
    id: "s6a",
    productId: "p6",
    platform: "Alibaba",
    supplierName: "JadeCraft Workshop",
    unitPrice: 2.4,
    moq: 100,
    currency: "USD",
    link: "https://www.alibaba.com",
    shippingCostPerUnit: 0.6,
    importDutyPct: 4.2,
    leadTimeDays: 16,
    rating: 4.9,
    inStock: true,
  },
  {
    id: "s6b",
    productId: "p6",
    platform: "IndiaMart",
    supplierName: "Natural Stone Exports",
    unitPrice: 3.1,
    moq: 50,
    currency: "USD",
    link: "https://www.indiamart.com",
    shippingCostPerUnit: 0.9,
    importDutyPct: 4.2,
    leadTimeDays: 21,
    rating: 4.4,
    inStock: true,
  },
  // RGB LED Strip
  {
    id: "s7a",
    productId: "p7",
    platform: "Alibaba",
    supplierName: "LEDWorld Shenzhen",
    unitPrice: 2.6,
    moq: 100,
    currency: "USD",
    link: "https://www.alibaba.com",
    shippingCostPerUnit: 0.8,
    importDutyPct: 3.9,
    leadTimeDays: 15,
    rating: 4.8,
    inStock: true,
  },
  {
    id: "s7b",
    productId: "p7",
    platform: "AliExpress",
    supplierName: "RGB Masters",
    unitPrice: 3.5,
    moq: 10,
    currency: "USD",
    link: "https://www.aliexpress.com",
    shippingCostPerUnit: 1.0,
    importDutyPct: 3.9,
    leadTimeDays: 20,
    rating: 4.6,
    inStock: true,
  },
  // Scalp Massager
  {
    id: "s8a",
    productId: "p8",
    platform: "Alibaba",
    supplierName: "WellnessGadgets Factory",
    unitPrice: 4.8,
    moq: 50,
    currency: "USD",
    link: "https://www.alibaba.com",
    shippingCostPerUnit: 1.2,
    importDutyPct: 3.7,
    leadTimeDays: 18,
    rating: 4.7,
    inStock: true,
  },
  {
    id: "s8b",
    productId: "p8",
    platform: "Made-in-China",
    supplierName: "HealthTech Exports",
    unitPrice: 5.3,
    moq: 30,
    currency: "USD",
    link: "https://www.made-in-china.com",
    shippingCostPerUnit: 1.3,
    importDutyPct: 3.7,
    leadTimeDays: 22,
    rating: 4.5,
    inStock: false,
  },
];
