import type { Species, CollectionSite, PlantSample, ExtractionBatch, AromaProfile, ChemistryResult, CommercialScore } from './types';

export const SEED_SPECIES: Species[] = [
  {
    id: 'sp-001',
    scientific_name: 'Mitrella mesnyi',
    common_name: 'Rumduol',
    khmer_name: 'ក្រមួន',
    family: 'Annonaceae',
    genus: 'Mitrella',
    description: 'Cambodia\'s national flower. A small evergreen tree bearing delicate yellow-cream flowers with an intensely sweet, nocturnal fragrance. Endemic to mainland Southeast Asia with highest concentration in Cambodia.',
    native_regions: ['Cambodia', 'Thailand', 'Vietnam', 'Laos'],
    conservation_status: 'Vulnerable',
    commercial_importance: 'Critical — national symbol with unique scent profile unmatched globally',
    notes: 'Blooms primarily at night; harvest window 20:00–04:00 for peak aromatic compounds. Enfleurage preferred to preserve top-note integrity.',
    created_at: '2024-01-15T08:00:00Z',
    updated_at: '2024-06-01T10:30:00Z',
  },
  {
    id: 'sp-002',
    scientific_name: 'Nelumbo nucifera',
    common_name: 'Sacred Lotus',
    khmer_name: 'ផ្កាប្ដំ',
    family: 'Nelumbonaceae',
    genus: 'Nelumbo',
    description: 'The sacred pink and white lotus holds deep spiritual significance across Cambodia. Aquatic perennial with distinctive aqueous-floral scent carrying earthy, clean undertones.',
    native_regions: ['Cambodia', 'India', 'China', 'Thailand', 'Vietnam'],
    conservation_status: 'Least Concern',
    commercial_importance: 'High — spiritual premium market, luxury perfumery, wellness export',
    notes: 'Harvested at dawn before fully opening. Pink variety yields higher aromatic concentration than white. Temple ponds and Tonle Sap margins are primary wild sources.',
    created_at: '2024-01-20T08:00:00Z',
    updated_at: '2024-05-15T14:00:00Z',
  },
  {
    id: 'sp-003',
    scientific_name: 'Cananga odorata',
    common_name: 'Ylang-Ylang',
    khmer_name: 'ក្លាំងខ្លឹម',
    family: 'Annonaceae',
    genus: 'Cananga',
    description: 'Tropical tree producing drooping yellow flowers with intensely sweet, banana-floral and rubbery scent. Widely used in Chanel No. 5 and other prestige perfumes.',
    native_regions: ['Cambodia', 'Philippines', 'Indonesia', 'Comoros', 'Madagascar'],
    conservation_status: 'Least Concern',
    commercial_importance: 'Very High — established global market, high yield economics',
    notes: 'Cambodian variety shows subtle differences from Comoros standard — earthier, less synthetic character. Early morning harvest (05:00–08:00) gives highest linalool fraction.',
    created_at: '2024-02-01T08:00:00Z',
    updated_at: '2024-06-10T09:00:00Z',
  },
  {
    id: 'sp-004',
    scientific_name: 'Styrax tonkinensis',
    common_name: 'Siam Benzoin',
    khmer_name: 'ស្ត្រុការ',
    family: 'Styracaceae',
    genus: 'Styrax',
    description: 'Medium tree producing a balsamic resin through bark tapping. Benzoin resin has a warm vanilla-balsam character and is critical in incense, fixative compounds, and oriental fragrances.',
    native_regions: ['Cambodia', 'Laos', 'Vietnam', 'China (Yunnan)', 'Thailand'],
    conservation_status: 'Near Threatened',
    commercial_importance: 'High — resin-based revenue, long shelf life, premium incense market',
    notes: 'Trees must be 7–10 years old before tapping. First tapping yields highest quality "head" resin. Mondulkiri province forests are primary source in Cambodia.',
    created_at: '2024-02-10T08:00:00Z',
    updated_at: '2024-04-20T11:00:00Z',
  },
  {
    id: 'sp-005',
    scientific_name: 'Pogostemon cablin',
    common_name: 'Patchouli',
    khmer_name: 'ប៉ាចូលី',
    family: 'Lamiaceae',
    genus: 'Pogostemon',
    description: 'Herbaceous perennial shrub with distinctive earthy, musky, slightly sweet scent. One of the most commercially important fragrance plants globally. Cambodian terroir may yield distinct chemical profile.',
    native_regions: ['Cambodia', 'Indonesia', 'India', 'Philippines', 'Malaysia'],
    conservation_status: 'Least Concern',
    commercial_importance: 'Very High — global commodity with strong Cambodia growth opportunity',
    notes: 'Dried leaves preferred for distillation. Fermentation of leaves before distillation increases patchoulol content. Kampot and Koh Kong coastal areas show promising results.',
    created_at: '2024-02-20T08:00:00Z',
    updated_at: '2024-06-05T16:00:00Z',
  },
  {
    id: 'sp-006',
    scientific_name: 'Coccinia grandis',
    common_name: 'Ivy Gourd',
    khmer_name: 'ប្រែក',
    family: 'Cucurbitaceae',
    genus: 'Coccinia',
    description: 'Climbing vine with white flowers and red fruit. While primarily known as a food plant, the flowers and leaves contain volatile aromatic compounds of growing interest to natural perfumers seeking unusual green and cucurbitaceous accords.',
    native_regions: ['Cambodia', 'India', 'Southeast Asia', 'Africa'],
    conservation_status: 'Least Concern',
    commercial_importance: 'Exploratory — niche green-floral accord potential, very limited competition',
    notes: 'Highly underresearched as fragrance plant. Flower volatiles peak mid-morning. Initial GC-MS shows interesting nonanal and 2-nonanone fractions. High-risk, high-differentiation opportunity.',
    created_at: '2024-03-01T08:00:00Z',
    updated_at: '2024-05-30T13:00:00Z',
  },
];

export const SEED_COLLECTION_SITES: CollectionSite[] = [
  {
    id: 'site-001',
    name: 'Siem Reap Temple Gardens',
    province: 'Siem Reap',
    district: 'Angkor',
    latitude: 13.4125,
    longitude: 103.8670,
    elevation_m: 35,
    habitat_type: 'Cultivated garden / temple grounds',
    soil_type: 'Sandy loam, well-drained',
    notes: 'Access requires coordination with APSARA authority. Plants near Banteay Srei show highest flowering density.',
    created_at: '2024-01-10T08:00:00Z',
  },
  {
    id: 'site-002',
    name: 'Tonle Sap Southern Margin',
    province: 'Kampong Chhnang',
    district: 'Rolea B\'ier',
    latitude: 12.2508,
    longitude: 104.6670,
    elevation_m: 8,
    habitat_type: 'Wetland / floating village perimeter',
    soil_type: 'Rich alluvial silt',
    notes: 'Seasonal access. Lotus harvest possible January–April before flood season. GPS coordinates are approximate — site accessible only by boat.',
    created_at: '2024-01-15T08:00:00Z',
  },
  {
    id: 'site-003',
    name: 'Mondulkiri Highland Reserve',
    province: 'Mondulkiri',
    district: 'Sen Monorom',
    latitude: 12.4619,
    longitude: 107.1878,
    elevation_m: 890,
    habitat_type: 'Highland evergreen forest',
    soil_type: 'Laterite, slightly acidic',
    notes: 'Protected area. Field permits required. Bunong community partnership for ethical collection. Benzoin trees at 800–1000m elevation.',
    created_at: '2024-01-20T08:00:00Z',
  },
  {
    id: 'site-004',
    name: 'Kampot Upland Farm',
    province: 'Kampot',
    district: 'Kampot',
    latitude: 10.5949,
    longitude: 104.1668,
    elevation_m: 120,
    habitat_type: 'Mixed cultivation / hillside farm',
    soil_type: 'Sandy clay, volcanic influence',
    notes: 'Partner farm. Patchouli cultivation plot established February 2024. Same microclimate that produces premium Kampot pepper.',
    created_at: '2024-02-01T08:00:00Z',
  },
  {
    id: 'site-005',
    name: 'Phnom Penh Botanical Station',
    province: 'Phnom Penh',
    district: 'Chamkarmon',
    latitude: 11.5449,
    longitude: 104.9282,
    elevation_m: 12,
    habitat_type: 'Research station / controlled garden',
    soil_type: 'Composted clay loam',
    notes: 'Royal University of Agriculture experimental plot. Controlled conditions. Ylang-Ylang and Rumduol comparison cultivation.',
    created_at: '2024-02-10T08:00:00Z',
  },
];

export const SEED_PLANT_SAMPLES: PlantSample[] = [
  {
    id: 'smp-001',
    sample_code: 'KBI-2024-RMD-001',
    species_id: 'sp-001',
    collection_site_id: 'site-001',
    collector_id: 'user-002',
    collector_name: 'Dara Sok',
    collected_at: '2024-03-15T22:30:00Z',
    plant_part: 'flower',
    flowering_stage: 'full_bloom',
    source_type: 'cultivated',
    quantity_g: 850,
    rainfall_mm: 12,
    temperature_c: 24.5,
    humidity_pct: 78,
    soil_notes: 'Sandy loam, well-irrigated. No fertiliser applied 30 days prior.',
    chain_of_custody: 'Collected by D. Sok → sealed glass jar → cold transport → received KBI lab 06:00 same day',
    photo_urls: [],
    notes: 'Exceptional bloom density this season. Flowers hand-picked individually to avoid stem contamination.',
    created_at: '2024-03-15T22:30:00Z',
    updated_at: '2024-03-16T06:00:00Z',
  },
  {
    id: 'smp-002',
    sample_code: 'KBI-2024-LTS-001',
    species_id: 'sp-002',
    collection_site_id: 'site-002',
    collector_id: 'user-002',
    collector_name: 'Dara Sok',
    collected_at: '2024-02-20T05:45:00Z',
    plant_part: 'flower',
    flowering_stage: 'early_bloom',
    source_type: 'wild',
    quantity_g: 1200,
    rainfall_mm: 0,
    temperature_c: 22.0,
    humidity_pct: 85,
    soil_notes: 'Rich alluvial silt. Flood-season residue still present.',
    chain_of_custody: 'Collected dawn → submerged in water transport → KBI lab 3hrs post-harvest',
    photo_urls: [],
    notes: 'Pink variety. Flowers harvested before petals fully separate. High density site on eastern margin.',
    created_at: '2024-02-20T05:45:00Z',
    updated_at: '2024-02-20T09:00:00Z',
  },
  {
    id: 'smp-003',
    sample_code: 'KBI-2024-YLG-001',
    species_id: 'sp-003',
    collection_site_id: 'site-005',
    collector_id: 'user-002',
    collector_name: 'Chan Phally',
    collected_at: '2024-04-10T06:15:00Z',
    plant_part: 'flower',
    flowering_stage: 'full_bloom',
    source_type: 'cultivated',
    quantity_g: 3200,
    rainfall_mm: 0,
    temperature_c: 28.0,
    humidity_pct: 72,
    soil_notes: 'Composted clay loam, pH 6.2',
    chain_of_custody: 'Machine-assisted harvest → weighed on-site → sealed → transported same morning',
    photo_urls: [],
    notes: 'Dry season harvest. Lower humidity may increase ester fraction. First harvest from the research plot.',
    created_at: '2024-04-10T06:15:00Z',
    updated_at: '2024-04-10T10:00:00Z',
  },
  {
    id: 'smp-004',
    sample_code: 'KBI-2024-BNZ-001',
    species_id: 'sp-004',
    collection_site_id: 'site-003',
    collector_id: 'user-002',
    collector_name: 'Sophea Meas',
    collected_at: '2024-05-08T09:00:00Z',
    plant_part: 'resin',
    flowering_stage: 'fruiting',
    source_type: 'semi_wild',
    quantity_g: 420,
    rainfall_mm: 45,
    temperature_c: 26.5,
    humidity_pct: 88,
    soil_notes: 'Laterite, pH 5.8. Trees at 900m elevation.',
    chain_of_custody: 'Tapping performed by Bunong partner → scraped after 72hr → sealed in amber glass',
    photo_urls: [],
    notes: 'First tapping of season — "head resin" quality. Trees approximately 12 years old. Vanilla note very pronounced.',
    created_at: '2024-05-08T09:00:00Z',
    updated_at: '2024-05-08T14:00:00Z',
  },
  {
    id: 'smp-005',
    sample_code: 'KBI-2024-PCH-001',
    species_id: 'sp-005',
    collection_site_id: 'site-004',
    collector_id: 'user-002',
    collector_name: 'Chan Phally',
    collected_at: '2024-06-01T08:00:00Z',
    plant_part: 'leaf',
    flowering_stage: 'pre_bud',
    source_type: 'cultivated',
    quantity_g: 5000,
    rainfall_mm: 28,
    temperature_c: 31.0,
    humidity_pct: 82,
    soil_notes: 'Sandy clay, good drainage, Kampot volcanic influence, pH 6.0',
    chain_of_custody: 'Machine harvest → 4-day shade dry → weighed → vacuum sealed → shipped to lab',
    photo_urls: [],
    notes: 'Dried on bamboo racks in shade. No fermentation applied for this first batch. Subsequent batch will test fermented vs unfermented.',
    created_at: '2024-06-01T08:00:00Z',
    updated_at: '2024-06-05T09:00:00Z',
  },
  {
    id: 'smp-006',
    sample_code: 'KBI-2024-CGR-001',
    species_id: 'sp-006',
    collection_site_id: 'site-005',
    collector_id: 'user-002',
    collector_name: 'Dara Sok',
    collected_at: '2024-06-12T09:30:00Z',
    plant_part: 'flower',
    flowering_stage: 'early_bloom',
    source_type: 'cultivated',
    quantity_g: 180,
    rainfall_mm: 15,
    temperature_c: 29.5,
    humidity_pct: 76,
    soil_notes: 'Composted clay loam, trellis-grown',
    chain_of_custody: 'Hand-harvested → immediately sealed in glass → cold transport within 2hrs',
    photo_urls: [],
    notes: 'Experimental collection. Very limited quantity. Primary objective is GC-MS fingerprint of flower volatiles.',
    created_at: '2024-06-12T09:30:00Z',
    updated_at: '2024-06-12T12:00:00Z',
  },
];

export const SEED_EXTRACTION_BATCHES: ExtractionBatch[] = [
  {
    id: 'ext-001',
    batch_code: 'KBI-EXT-2024-001',
    plant_sample_id: 'smp-001',
    species_id: 'sp-001',
    method: 'enfleurage',
    raw_weight_g: 850,
    final_weight_g: 2.1,
    yield_pct: 0.247,
    duration_hours: 48,
    temperature_c: 22,
    pressure_bar: null,
    solvent_used: 'Cold pomade (refined lard)',
    operator_id: 'user-003',
    operator_name: 'Dr. Lina Var',
    extraction_date: '2024-03-16',
    output_type: 'absolute',
    colour: 'Pale golden yellow',
    clarity: 'Clear',
    notes: 'Traditional enfleurage. 48hr maceration with 2 flower refreshes. Final absolute via ethanol wash. Exceptional top-note retention.',
    created_at: '2024-03-16T08:00:00Z',
  },
  {
    id: 'ext-002',
    batch_code: 'KBI-EXT-2024-002',
    plant_sample_id: 'smp-002',
    species_id: 'sp-002',
    method: 'steam_distillation',
    raw_weight_g: 1200,
    final_weight_g: 0.96,
    yield_pct: 0.080,
    duration_hours: 4,
    temperature_c: 100,
    pressure_bar: 1.0,
    solvent_used: null,
    operator_id: 'user-003',
    operator_name: 'Dr. Lina Var',
    extraction_date: '2024-02-20',
    output_type: 'essential_oil',
    colour: 'Very pale yellow, almost colourless',
    clarity: 'Clear',
    notes: 'Low yield typical of lotus petals. Mild steam to protect terpenoid fraction. Hydrosol also retained for separate analysis.',
    created_at: '2024-02-20T10:00:00Z',
  },
  {
    id: 'ext-003',
    batch_code: 'KBI-EXT-2024-003',
    plant_sample_id: 'smp-003',
    species_id: 'sp-003',
    method: 'steam_distillation',
    raw_weight_g: 3200,
    final_weight_g: 67.2,
    yield_pct: 2.1,
    duration_hours: 3,
    temperature_c: 100,
    pressure_bar: 1.0,
    solvent_used: null,
    operator_id: 'user-003',
    operator_name: 'Dr. Lina Var',
    extraction_date: '2024-04-10',
    output_type: 'essential_oil',
    colour: 'Yellow to amber',
    clarity: 'Slightly hazy — decants clear after 24hrs',
    notes: 'Good yield for ylang. Three fractions collected (Extra, I, II). This batch combines all fractions for baseline analysis.',
    created_at: '2024-04-10T12:00:00Z',
  },
  {
    id: 'ext-004',
    batch_code: 'KBI-EXT-2024-004',
    plant_sample_id: 'smp-004',
    species_id: 'sp-004',
    method: 'ethanol_tincture',
    raw_weight_g: 420,
    final_weight_g: 126.0,
    yield_pct: 30.0,
    duration_hours: 336,
    temperature_c: 18,
    pressure_bar: null,
    solvent_used: 'Food-grade ethanol 96%',
    operator_id: 'user-003',
    operator_name: 'Dr. Lina Var',
    extraction_date: '2024-05-08',
    output_type: 'tincture',
    colour: 'Deep amber-brown',
    clarity: 'Clear after filtration',
    notes: '14-day cold maceration in ethanol. Benzoin resin dissolves cleanly. Strong vanilla-balsam character. Residue tested separately.',
    created_at: '2024-05-08T15:00:00Z',
  },
  {
    id: 'ext-005',
    batch_code: 'KBI-EXT-2024-005',
    plant_sample_id: 'smp-005',
    species_id: 'sp-005',
    method: 'steam_distillation',
    raw_weight_g: 5000,
    final_weight_g: 75.0,
    yield_pct: 1.5,
    duration_hours: 6,
    temperature_c: 100,
    pressure_bar: 1.0,
    solvent_used: null,
    operator_id: 'user-003',
    operator_name: 'Dr. Lina Var',
    extraction_date: '2024-06-05',
    output_type: 'essential_oil',
    colour: 'Dark olive green to amber',
    clarity: 'Clear',
    notes: 'Unfermented batch. Yield slightly below expected — fermentation protocol to be tested on next batch. Earthy character dominant.',
    created_at: '2024-06-05T14:00:00Z',
  },
];

export const SEED_AROMA_PROFILES: AromaProfile[] = [
  {
    id: 'aro-001',
    extraction_batch_id: 'ext-001',
    species_id: 'sp-001',
    evaluator_name: 'Dr. Lina Var',
    evaluation_date: '2024-03-20',
    top_notes: ['Honey', 'Sweet floral', 'Gardenia-like', 'Faint citrus'],
    heart_notes: ['Tuberose', 'Jasmine', 'Creamy', 'Neroli'],
    base_notes: ['Musky', 'Woody', 'Subtle vanilla'],
    intensity: 9,
    longevity: 8,
    uniqueness: 10,
    luxury_score: 10,
    overall_score: 9.25,
    perfumer_notes: 'Extraordinary. Unlike any commercial floral absolute currently on market. The nocturnal sweetness is distinctive — not indolic like jasmine, not aldehydic like tuberose. A genuine discovery. Top note fades after 30 min but heart is tenacious. Enfleurage absolutely the correct method.',
    created_at: '2024-03-20T14:00:00Z',
  },
  {
    id: 'aro-002',
    extraction_batch_id: 'ext-002',
    species_id: 'sp-002',
    evaluator_name: 'Dr. Lina Var',
    evaluation_date: '2024-02-25',
    top_notes: ['Aqueous', 'Clean', 'Green', 'Light floral'],
    heart_notes: ['Rose-like', 'Soft powder', 'Watery floral'],
    base_notes: ['Earthy', 'Root-like', 'Clean musk'],
    intensity: 5,
    longevity: 4,
    uniqueness: 7,
    luxury_score: 8,
    overall_score: 6.0,
    perfumer_notes: 'Quintessentially "clean". Lotus oil is delicate — will disappear quickly in a blend without proper fixation. The watery-floral character is genuine and irreplaceable. High-quality accord or headspace extraction would serve this plant better than steam distillation.',
    created_at: '2024-02-25T11:00:00Z',
  },
  {
    id: 'aro-003',
    extraction_batch_id: 'ext-003',
    species_id: 'sp-003',
    evaluator_name: 'Dr. Lina Var',
    evaluation_date: '2024-04-15',
    top_notes: ['Banana', 'Sweet', 'Bright floral', 'Eugenol spice'],
    heart_notes: ['Creamy', 'Jasmine-like', 'Rubber', 'Heavy floral'],
    base_notes: ['Musky', 'Woody', 'Earthy'],
    intensity: 8,
    longevity: 9,
    uniqueness: 6,
    luxury_score: 7,
    overall_score: 7.5,
    perfumer_notes: 'Classic ylang character — recognisable globally. Cambodian sample shows slightly earthier, less synthetic rubber note than Comoros standard. This may be marketable as a "cleaner" ylang profile. High linalool fraction suggests quality. Strong performance in diluted accords.',
    created_at: '2024-04-15T10:00:00Z',
  },
  {
    id: 'aro-004',
    extraction_batch_id: 'ext-004',
    species_id: 'sp-004',
    evaluator_name: 'Dr. Lina Var',
    evaluation_date: '2024-05-15',
    top_notes: ['Vanilla', 'Sweet balsam', 'Faint smoke'],
    heart_notes: ['Warm resin', 'Cinnamon', 'Caramel', 'Peru balsam'],
    base_notes: ['Deep balsam', 'Oakmoss-like', 'Incense', 'Dark wood'],
    intensity: 7,
    longevity: 10,
    uniqueness: 7,
    luxury_score: 8,
    overall_score: 8.0,
    perfumer_notes: 'Excellent fixative character. Benzoin tincture is a classic material — this Cambodian batch has exceptional vanilla depth. The incense undertone is more pronounced than Laos sources. Outstanding base note anchor for oriental compositions. Very good commercial viability as a resin ingredient.',
    created_at: '2024-05-15T14:00:00Z',
  },
  {
    id: 'aro-005',
    extraction_batch_id: 'ext-005',
    species_id: 'sp-005',
    evaluator_name: 'Dr. Lina Var',
    evaluation_date: '2024-06-08',
    top_notes: ['Earthy', 'Dark', 'Woody', 'Slightly herbaceous'],
    heart_notes: ['Musky', 'Earthy', 'Tobacco-like', 'Chocolate note'],
    base_notes: ['Deep earth', 'Camphoreous', 'Animalic', 'Persistent wood'],
    intensity: 8,
    longevity: 10,
    uniqueness: 6,
    luxury_score: 6,
    overall_score: 7.5,
    perfumer_notes: 'Solid patchouli character. Slightly greener and less sweet than aged Indonesian. Unfermented profile evident — the "green" top is more pronounced. Will benefit from 6-month aging. Kampot terroir shows subtle pepper-adjacent mineral note in the drydown. Interesting differentiation potential.',
    created_at: '2024-06-08T10:00:00Z',
  },
];

export const SEED_CHEMISTRY_RESULTS: ChemistryResult[] = [
  {
    id: 'chem-001',
    extraction_batch_id: 'ext-001',
    species_id: 'sp-001',
    compound_name: 'Linalool',
    cas_number: '78-70-6',
    percentage: 28.4,
    detection_method: 'gc_ms',
    lab_name: 'KBI Internal Laboratory',
    analysis_date: '2024-03-22',
    certificate_url: null,
    notes: 'Primary floral component. High concentration consistent with sweet-honey character.',
    created_at: '2024-03-22T16:00:00Z',
  },
  {
    id: 'chem-002',
    extraction_batch_id: 'ext-001',
    species_id: 'sp-001',
    compound_name: 'Benzyl acetate',
    cas_number: '140-11-4',
    percentage: 18.7,
    detection_method: 'gc_ms',
    lab_name: 'KBI Internal Laboratory',
    analysis_date: '2024-03-22',
    certificate_url: null,
    notes: 'Jasmine-type ester. Contributes sweet, fruity floral character.',
    created_at: '2024-03-22T16:00:00Z',
  },
  {
    id: 'chem-003',
    extraction_batch_id: 'ext-001',
    species_id: 'sp-001',
    compound_name: 'Methyl benzoate',
    cas_number: '93-58-3',
    percentage: 12.3,
    detection_method: 'gc_ms',
    lab_name: 'KBI Internal Laboratory',
    analysis_date: '2024-03-22',
    certificate_url: null,
    notes: 'Distinctive compound — high levels unusual in floral absolutes. Contributes the honeyed quality.',
    created_at: '2024-03-22T16:00:00Z',
  },
  {
    id: 'chem-004',
    extraction_batch_id: 'ext-003',
    species_id: 'sp-003',
    compound_name: 'Linalool',
    cas_number: '78-70-6',
    percentage: 31.2,
    detection_method: 'gc_ms',
    lab_name: 'KBI Internal Laboratory',
    analysis_date: '2024-04-18',
    certificate_url: null,
    notes: 'Highest detected compound. Indicates good quality distillation.',
    created_at: '2024-04-18T14:00:00Z',
  },
  {
    id: 'chem-005',
    extraction_batch_id: 'ext-003',
    species_id: 'sp-003',
    compound_name: 'Benzyl acetate',
    cas_number: '140-11-4',
    percentage: 19.8,
    detection_method: 'gc_ms',
    lab_name: 'KBI Internal Laboratory',
    analysis_date: '2024-04-18',
    certificate_url: null,
    notes: '',
    created_at: '2024-04-18T14:00:00Z',
  },
  {
    id: 'chem-006',
    extraction_batch_id: 'ext-003',
    species_id: 'sp-003',
    compound_name: 'Germacrene D',
    cas_number: '23986-74-5',
    percentage: 8.6,
    detection_method: 'gc_ms',
    lab_name: 'KBI Internal Laboratory',
    analysis_date: '2024-04-18',
    certificate_url: null,
    notes: 'Sesquiterpene common in ylang. Contributes woody-earthy character.',
    created_at: '2024-04-18T14:00:00Z',
  },
  {
    id: 'chem-007',
    extraction_batch_id: 'ext-005',
    species_id: 'sp-005',
    compound_name: 'Patchoulol',
    cas_number: '5986-55-0',
    percentage: 32.4,
    detection_method: 'gc_ms',
    lab_name: 'KBI Internal Laboratory',
    analysis_date: '2024-06-10',
    certificate_url: null,
    notes: 'Primary sesquiterpene alcohol. Slightly lower than expected — fermentation should increase this.',
    created_at: '2024-06-10T12:00:00Z',
  },
  {
    id: 'chem-008',
    extraction_batch_id: 'ext-005',
    species_id: 'sp-005',
    compound_name: 'α-Bulnesene',
    cas_number: '3691-12-1',
    percentage: 18.1,
    detection_method: 'gc_ms',
    lab_name: 'KBI Internal Laboratory',
    analysis_date: '2024-06-10',
    certificate_url: null,
    notes: 'Sesquiterpene hydrocarbon contributing earthy character.',
    created_at: '2024-06-10T12:00:00Z',
  },
];

export const SEED_COMMERCIAL_SCORES: CommercialScore[] = [
  {
    id: 'com-001',
    species_id: 'sp-001',
    evaluator_name: 'Damian Guardiangs',
    evaluation_date: '2024-04-01',
    rarity: 10,
    yield_economics: 3,
    scent_quality: 10,
    supply_scalability: 4,
    regulatory_risk: 5,
    export_potential: 9,
    brand_fit: 10,
    overall_score: 7.3,
    market_notes: 'The crown jewel. Zero global competition. Yield economics are challenging but the scarcity is the asset. Prioritise brand story and ultra-premium positioning. Target Maison perfumers and niche houses. DO NOT commoditise.',
    created_at: '2024-04-01T10:00:00Z',
  },
  {
    id: 'com-002',
    species_id: 'sp-002',
    evaluator_name: 'Damian Guardiangs',
    evaluation_date: '2024-04-01',
    rarity: 5,
    yield_economics: 2,
    scent_quality: 7,
    supply_scalability: 5,
    regulatory_risk: 2,
    export_potential: 7,
    brand_fit: 8,
    overall_score: 5.1,
    market_notes: 'Spiritual premium angle. Very low yield limits bulk commercial play. Best positioned as sacred ingredient in ultra-niche collaboration. Cambodia angle is strong. Do not chase lotus oil — pursue live-capture accords instead.',
    created_at: '2024-04-01T10:00:00Z',
  },
  {
    id: 'com-003',
    species_id: 'sp-003',
    evaluator_name: 'Damian Guardiangs',
    evaluation_date: '2024-04-01',
    rarity: 4,
    yield_economics: 9,
    scent_quality: 8,
    supply_scalability: 9,
    regulatory_risk: 2,
    export_potential: 9,
    brand_fit: 7,
    overall_score: 6.9,
    market_notes: 'Strong commercial backbone. Ylang is established globally — Cambodia must differentiate on terroir story and clean profile. Good economics. Could be flagship export ingredient to supplement premium offerings. Bulk + niche dual channel.',
    created_at: '2024-04-01T10:00:00Z',
  },
  {
    id: 'com-004',
    species_id: 'sp-004',
    evaluator_name: 'Damian Guardiangs',
    evaluation_date: '2024-04-01',
    rarity: 6,
    yield_economics: 7,
    scent_quality: 8,
    supply_scalability: 6,
    regulatory_risk: 3,
    export_potential: 8,
    brand_fit: 8,
    overall_score: 6.6,
    market_notes: 'Excellent resin economics once trees are established. Long shelf life. Incense and oriental fragrance markets are robust. Cambodia benzoin has real GI potential — pursue Geographical Indication with government. Mondulkiri sourcing story is compelling.',
    created_at: '2024-04-01T10:00:00Z',
  },
  {
    id: 'com-005',
    species_id: 'sp-005',
    evaluator_name: 'Damian Guardiangs',
    evaluation_date: '2024-04-01',
    rarity: 4,
    yield_economics: 8,
    scent_quality: 7,
    supply_scalability: 9,
    regulatory_risk: 2,
    export_potential: 8,
    brand_fit: 6,
    overall_score: 6.3,
    market_notes: 'Best economics in the portfolio. Kampot patchouli could become a commercially significant brand — leverage the Kampot pepper premium precedent. Needs aging program and distinctive terroir narrative. Scale quickly to establish supply position.',
    created_at: '2024-04-01T10:00:00Z',
  },
  {
    id: 'com-006',
    species_id: 'sp-006',
    evaluator_name: 'Damian Guardiangs',
    evaluation_date: '2024-04-01',
    rarity: 9,
    yield_economics: 2,
    scent_quality: 5,
    supply_scalability: 4,
    regulatory_risk: 2,
    export_potential: 4,
    brand_fit: 6,
    overall_score: 4.6,
    market_notes: 'High-risk research play. The green-floral accord potential is genuinely novel. Maintain as a portfolio curiosity and R&D investment — not a commercial priority yet. Revisit after second GC-MS confirms initial findings.',
    created_at: '2024-04-01T10:00:00Z',
  },
];
